directives:
  - "docs/coding-standards.md"
  - "docs/review-guidelines.md"

exclusions:
  - "tests/"
  - "t/"
  - "build/"
  - "README.md"

llm_parameters:
  temperature: 0.8
  max_tokens: 1500
  model_name: "gpt-4"

llm_backends:

  - backend_name: "HuggingFace"
    model_name: ""
    token: "TOKEN"
    url: "https://api-inference.huggingface.co/models/meta-llama/Meta-Llama-3-8B-Instruct"
    # url: "https://api-inference.huggingface.co/models/meta-llama/Llama-2-7b-hf"
    # url: "https://api-inference.huggingface.co/models/meta-llama/Llama-3.3-70B-Instruct"
    # url: "https://api-inference.huggingface.co/models/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"

update_frequency: "daily"
