name: Pull Request Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-and-review:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code-review

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Validate the configuration file
      - name: Validate configuration
        run: |
          python core/config_validator.py

      # Step 5: Execute the review agent
      - name: Run review agent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          python core/review_agent.py
